package PANTALLAS;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex0
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        Transparente();
    }
   public void Transparente ()
{
btnADE.setOpaque(false);
btnADE.setContentAreaFilled(false);
btnADE.setBorderPainted(false);
btnAM.setOpaque(false);
btnAM.setContentAreaFilled(false);
btnAM.setBorderPainted(false);

btnAPE.setOpaque(false);
btnAPE.setContentAreaFilled(false);
btnAPE.setBorderPainted(false);
btnP.setOpaque(false);
btnP.setContentAreaFilled(false);
btnP.setBorderPainted(false);

btnCPE.setOpaque(false);
btnCPE.setContentAreaFilled(false);
btnCPE.setBorderPainted(false);
btnCMG.setOpaque(false);
btnCMG.setContentAreaFilled(false);
btnCMG.setBorderPainted(false);
btnR.setOpaque(false);
btnR.setContentAreaFilled(false);
btnR.setBorderPainted(false);
btnSalir.setOpaque(false);
btnSalir.setContentAreaFilled(false);
btnSalir.setBorderPainted(false);


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnADE = new javax.swing.JButton();
        btnAM = new javax.swing.JButton();
        btnAPE = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnCPE = new javax.swing.JButton();
        btnCMG = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnADE.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnADE.setText(" ACTUAIZADOR\n DE ENTRENADOR");
        btnADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADEActionPerformed(evt);
            }
        });
        getContentPane().add(btnADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 30));

        btnAM.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnAM.setText("ACTUALIZAR MEDALLAS");
        getContentPane().add(btnAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 150, 30));

        btnAPE.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnAPE.setText("ACTUALIZAR POKÉMON/ENTRENADOR ");
        getContentPane().add(btnAPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 220, 30));

        btnP.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnP.setText("ACTUALIZAR POKÉMON");
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });
        getContentPane().add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        btnCPE.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnCPE.setText("CONSULTAR POKÉMON\n/ENTRENADOR"); // NOI18N
        getContentPane().add(btnCPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 230, 30));

        btnCMG.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnCMG.setText("CONSULTAR MEDALLAS GANADAS");
        getContentPane().add(btnCMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        btnR.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btnR.setText("REPORTES ");
        getContentPane().add(btnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        btnSalir.setText(".");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 403, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENUNU.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        ACTUALIZADORES.AcMenuPokemon Ventana = new ACTUALIZADORES.AcMenuPokemon();
        Ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPActionPerformed

    private void btnADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADEActionPerformed
        ACTUALIZADORES.AcMenuEntrenador Ventana = new ACTUALIZADORES.AcMenuEntrenador();
        Ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnADEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADE;
    private javax.swing.JButton btnAM;
    private javax.swing.JButton btnAPE;
    private javax.swing.JButton btnCMG;
    private javax.swing.JButton btnCPE;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
